name: terraform.yaml
on:
  push:
    branches:
      - main

env:
  # Expose environment variables that could be used in script execution
  TEMPORAL_API_KEY: ${{ secrets.TEMPORAL_API_KEY }}
  # AWS Environment variables used for backend storage
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    name: "Terraform Infrastructure Change Management"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 'latest'

      # Version Iterate all directories and run terraform commands
      - name: Find directories and run Terraform init
        run: |
          find ./terraform -mindepth 1 -maxdepth 2 -type d -exec sh -c '
            echo "Processing directory: {}"
            cd "{}"
            terraform init
          ' \;

      - name: Find directories and run Terraform format
        run: |
          find ./terraform -mindepth 1 -maxdepth 2 -type d -exec sh -c '
            echo "Processing directory: {}"
            cd "{}"
            terraform fmt -check
          ' \;

      - name: Find directories and run Terraform validate
        run: |
          find ./terraform -mindepth 1 -maxdepth 2 -type d -exec sh -c '
            echo "Processing directory: {}"
            cd "{}"
            terraform validate
          ' \;


      - name: Find directories and run Terraform plan
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          find ./terraform -mindepth 1 -maxdepth 2 -type d -exec sh -c '
            echo "Processing directory: {}"
            cd "{}"
            terraform plan
          ' \;

      - name: Find directories and run Terraform apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          find ./terraform -mindepth 1 -maxdepth 2 -type d -exec sh -c '
            echo "Processing directory: {}"
            cd "{}"
            terraform apply -auto-approve -input=false
          ' \;

      

